# Copyright (c) Trainline Limited, 2016-2017. All rights reserved. See LICENSE.txt in the project root for license information.

version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rollingFile:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    when: midnight
    filename: 'C:/TTLLogs/consul-deployment-agent.log'
root:
  level: DEBUG
  handlers: [console, rollingFile]
