# Copyright (c) Trainline Limited, 2016. All rights reserved. See LICENSE.txt in the project root for license information.

aws:
  # Credential for accessing S3. If not specified, IAM role on EC2 instance where agent is running will be used.
  access_key_id: some_access_key_id
  aws_secret_access_key: some_aws_secret_access_key
  # Deployment log shipping location. If not specified, logs will not be shipped to S3
  deployment_logs:
    bucket_name: some-bucket-name
    key_prefix: deployments
consul:
  # Consul ACL token configuration. If not specified, no token will be used to access Consul key-value store.
  acl_token: some_acl_token
startup:
  # Path of the file used to signal instance readiness
  semaphore_filepath: /some/path/semaphore.txt
  # Set to true to wait for instance readiness before triggering deployments. False otherwise.
  wait_for_instance_readiness: true
